// All configuration in one place — edit this to tune the tracker.

export const CONFIG = {
  // Sources to fetch from
  sources: {
    remoteok: { enabled: true },
    weworkremotely: { enabled: true },
    larajobs: { enabled: true },
    laravelio: { enabled: false },   // disabled — site structure changed, not fixed
    remotive: { enabled: true },        // NEW
    workingnomads: { enabled: true },   // NEW
    jobspresso: { enabled: true },      // NEW
    productjobsanywhere: { enabled: true },
    workable: {
      enabled: true,
      queries: [
        "laravel",
        "php developer",
        "backend engineer",
        "product engineer",
        "full stack",
        "fullstack",
      ],
      locations: ["", "Africa"],
    },
  },

  spreadsheet: {
    backendSheetName: "Backend Jobs",
    productSheetName: "Product Jobs",
    todaySheetName: "Today",
    stretchSheetName: "Stretch Roles",
    rejectedSheetName: "Rejected Jobs",
    archiveSheetName: "Archived Jobs",
    sourceHealthSheetName: "Source Health",
    resetEveryMonths: 2,
    rejectedRetentionDays: 30,
  },

  privateRegistry: {
    applicationsSheetName: "Applications",
    excludedCompaniesSheetName: "Excluded Companies",
    rejectionCooldownMonths: 6,
  },

  matching: {
    dailyShortlistLimit: 10,
    maxRowsPerCompany: 3,
    recommendations: {
      applyToday: 80,
      strongMatch: 65,
      manualReview: 50,
    },
    sourcePreference: [
      "Product Jobs Anywhere",
      "Larajobs",
      "Laravel.io",
      "WeWorkRemotely",
      "RemoteOK",
      "Remotive",
      "WorkingNomads",
      "Jobspresso",
      "Workable",
    ],
    strongSkills: [
      "php",
      "laravel",
      "symfony",
      "mysql",
      "rest api",
      "restful api",
      "redis",
      "kafka",
      "rabbitmq",
      "cqrs",
      "event-driven",
      "event driven",
      "ddd",
      "domain-driven",
      "docker",
      "ci/cd",
      "github actions",
    ],
    transferableSkills: [
      "node.js",
      "nodejs",
      "typescript",
      "javascript",
      "postgresql",
      "postgres",
      "aws",
      "react",
      "vue",
      "observability",
      "datadog",
      "sentry",
    ],
    preferredDomains: [
      "saas",
      "e-commerce",
      "ecommerce",
      "commerce",
      "marketplace",
      "fintech",
      "financial",
      "payments",
      "travel",
      "hospitality",
      "food-tech",
      "food tech",
    ],
    productOwnershipSignals: [
      "product-minded",
      "product minded",
      "end-to-end",
      "end to end",
      "0-to-1",
      "zero to one",
      "requirements discovery",
      "customer problems",
      "customer-facing",
      "customer facing",
      "business requirements",
      "domain modeling",
      "technical trade-offs",
      "technical tradeoffs",
      "ownership",
      "own features",
      "cross-functional",
      "cross functional",
      "ambiguous",
      "mvp",
    ],
  },

  // How many days back to keep listings
  maxAgeDays: 30,
};
